on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy (dev or prod)"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: environments/${{ github.event.inputs.environment }}

      - name: Terraform Plan
        run: terraform plan 
        working-directory: environments/${{ github.event.inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve 
        working-directory: environments/${{ github.event.inputs.environment }}